"""Static site generator behavior is documented with filesystem-level tests."""

from __future__ import annotations

import tempfile
import unittest
from pathlib import Path

from main import FatalBuildError, build_site, check_source, project_path


class StaticSiteGeneratorTest(unittest.TestCase):
    def test_markdown_heading_becomes_page_title_with_single_h1(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            source = root / "content"
            output = root / "public"
            source.mkdir()
            (source / "report.md").write_text("# Trip Plan\n\nBody text.\n", encoding="utf-8")

            build_site(source, output)

            html = (output / "report.html").read_text(encoding="utf-8")
            self.assertIn("Template for generated static HTML pages", html)
            self.assertIn("<title>Trip Plan | Library Presentator</title>", html)
            self.assertNotIn("Generated by library-presentator.", html)
            self.assertIn('class="page-meta">生成日: <time datetime="', html)
            self.assertIn('class="copy-button" data-copy-content="copy-source"', html)
            self.assertIn("Markdownをコピー", html)
            self.assertIn('<textarea id="copy-source" class="copy-source" hidden readonly>', html)
            self.assertIn("# Trip Plan\n\nBody text.\n</textarea>", html)
            self.assertIn('<div id="content-body" class="content-body">', html)
            self.assertIn('<nav class="toc" aria-labelledby="toc-title">', html)
            self.assertIn('<a href="#heading-1">Trip Plan</a>', html)
            self.assertEqual(html.count("<h1>"), 1)
            self.assertIn('<h2 id="heading-1">Trip Plan</h2>', html)

    def test_front_matter_title_has_priority_over_heading(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            source = root / "content"
            output = root / "public"
            source.mkdir()
            (source / "report.md").write_text(
                "---\ntitle: Front Matter Title\ntags: [travel, report]\n---\n# Heading Title\n",
                encoding="utf-8",
            )

            build_site(source, output)

            html = (output / "report.html").read_text(encoding="utf-8")
            self.assertIn("<h1>Front Matter Title</h1>", html)

    def test_csv_becomes_table_and_links_http_cells(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            source = root / "content"
            output = root / "public"
            source.mkdir()
            (source / "books.csv").write_text(
                "title,url,notes\nExample,https://example.com/?a=1&b=2,<unsafe>\n",
                encoding="utf-8",
            )

            build_site(source, output)

            html = (output / "books.html").read_text(encoding="utf-8")
            self.assertIn('class="page-meta">生成日: <time datetime="', html)
            self.assertIn("Markdownをコピー", html)
            self.assertIn("| title | url | notes |\n| --- | --- | --- |", html)
            self.assertIn("https://example.com/?a=1&amp;b=2", html)
            self.assertNotIn('<nav class="toc"', html)
            self.assertIn("<table>", html)
            self.assertIn('<th scope="col">title</th>', html)
            self.assertIn(
                '<a href="https://example.com/?a=1&amp;b=2">https://example.com/?a=1&amp;b=2</a>',
                html,
            )
            self.assertIn("&lt;unsafe&gt;", html)

    def test_static_file_is_copied_with_relative_path(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            source = root / "content"
            output = root / "public"
            nested = source / "files"
            nested.mkdir(parents=True)
            (nested / "note.txt").write_text("plain text", encoding="utf-8")

            build_site(source, output)

            self.assertEqual((output / "files" / "note.txt").read_text(encoding="utf-8"), "plain text")

    def test_default_static_assets_are_copied_from_static_sources(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            source = root / "content"
            output = root / "public"
            source.mkdir()

            build_site(source, output)

            self.assertEqual(
                (output / "static" / "style.css").read_text(encoding="utf-8"),
                project_path("static", "style.css").read_text(encoding="utf-8"),
            )
            self.assertEqual(
                (output / "static" / "script.js").read_text(encoding="utf-8"),
                project_path("static", "script.js").read_text(encoding="utf-8"),
            )

    def test_invalid_csv_is_reported_but_valid_pages_are_generated(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            source = root / "content"
            output = root / "public"
            source.mkdir()
            (source / "ok.md").write_text("# OK\n", encoding="utf-8")
            (source / "bad.csv").write_text("a,b\n1\n", encoding="utf-8")

            result = build_site(source, output)

            self.assertEqual(len(result.errors), 1)
            self.assertTrue((output / "ok.html").exists())
            errors_html = (output / "errors.html").read_text(encoding="utf-8")
            self.assertIn("bad.csv", errors_html)
            self.assertIn("ColumnCountMismatch", errors_html)

    def test_output_path_collision_is_reported(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            source = root / "content"
            source.mkdir()
            (source / "same.csv").write_text("title\nA\n", encoding="utf-8")
            (source / "same.md").write_text("# Same\n", encoding="utf-8")

            errors = check_source(source, root / "public")

            self.assertEqual(len(errors), 1)
            self.assertEqual(errors[0].error_type, "Collision")

    def test_output_directory_inside_source_is_fatal(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            source = Path(temp) / "content"
            source.mkdir()

            with self.assertRaises(FatalBuildError):
                build_site(source, source / "public")


if __name__ == "__main__":
    unittest.main()
