"""Static site generator behavior is documented with filesystem-level tests."""

from __future__ import annotations

import json
import tempfile
import unittest
from pathlib import Path

from main import FatalBuildError, build_site, check_source, project_path


class StaticSiteGeneratorTest(unittest.TestCase):
    def test_markdown_heading_becomes_page_title_with_single_h1(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            source = root / "content"
            output = root / "public"
            source.mkdir()
            (source / "report.md").write_text("# Trip Plan\n\nBody text.\n", encoding="utf-8")

            build_site(source, output)

            html = (output / "report.html").read_text(encoding="utf-8")
            self.assertIn("Template for generated static HTML pages", html)
            self.assertIn("<title>Trip Plan | fbinder</title>", html)
            self.assertNotIn("Generated by fbinder.", html)
            self.assertIn('class="page-meta">生成日: <time datetime="', html)
            self.assertIn('class="copy-button" data-copy-content="copy-source"', html)
            self.assertIn('class="copy-button" data-copy-content="copy-source-path"', html)
            self.assertIn("Markdownをコピー", html)
            self.assertIn("パスをコピー", html)
            self.assertIn('<textarea id="copy-source" class="copy-source" hidden readonly>', html)
            self.assertIn("# Trip Plan\n\nBody text.\n</textarea>", html)
            self.assertIn('<textarea id="copy-source-path" class="copy-source" hidden readonly>report.md</textarea>', html)
            self.assertIn('<div id="content-body" class="content-body">', html)
            self.assertIn('<nav class="toc" aria-labelledby="toc-title">', html)
            self.assertIn('<a href="#heading-1">Trip Plan</a>', html)
            self.assertEqual(html.count("<h1>"), 1)
            self.assertIn('<h2 id="heading-1">Trip Plan</h2>', html)

    def test_front_matter_title_has_priority_over_heading(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            source = root / "content"
            output = root / "public"
            source.mkdir()
            (source / "report.md").write_text(
                "---\ntitle: Front Matter Title\ntags: [travel, report]\n---\n# Heading Title\n",
                encoding="utf-8",
            )

            build_site(source, output)

            html = (output / "report.html").read_text(encoding="utf-8")
            self.assertIn("<h1>Front Matter Title</h1>", html)

    def test_front_matter_favorite_marks_detail_and_index(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            source = root / "content"
            output = root / "public"
            source.mkdir()
            (source / "regular.md").write_text("# Regular\n", encoding="utf-8")
            (source / "favorite.md").write_text(
                "---\nfavorite: true\n---\n# Favorite\n",
                encoding="utf-8",
            )

            build_site(source, output)

            favorite_html = (output / "favorite.html").read_text(encoding="utf-8")
            index_html = (output / "index.html").read_text(encoding="utf-8")
            self.assertIn(
                '<span class="favorite-label" aria-label="お気に入り">★ お気に入り</span>',
                favorite_html,
            )
            self.assertIn(
                '<span class="favorite-marker" aria-label="お気に入り" title="お気に入り">★</span>',
                index_html,
            )
            self.assertLess(index_html.index("Favorite"), index_html.index("Regular"))

            search_index = json.loads((output / "search-index.json").read_text(encoding="utf-8"))
            favorite_item = next(item for item in search_index["items"] if item["title"] == "Favorite")
            self.assertNotIn("true", favorite_item["text"])

    def test_csv_becomes_table_and_links_http_cells(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            source = root / "content"
            output = root / "public"
            source.mkdir()
            (source / "books.csv").write_text(
                "title,url,notes\nExample,https://example.com/?a=1&b=2,<unsafe>\n",
                encoding="utf-8",
            )

            build_site(source, output)

            html = (output / "books.html").read_text(encoding="utf-8")
            self.assertIn('class="page-meta">生成日: <time datetime="', html)
            self.assertIn("Markdownをコピー", html)
            self.assertIn("| title | url | notes |\n| --- | --- | --- |", html)
            self.assertIn("https://example.com/?a=1&amp;b=2", html)
            self.assertNotIn('<nav class="toc"', html)
            self.assertIn("<table>", html)
            self.assertIn('<th scope="col">title</th>', html)
            self.assertIn(
                '<a href="https://example.com/?a=1&amp;b=2">https://example.com/?a=1&amp;b=2</a>',
                html,
            )
            self.assertIn("&lt;unsafe&gt;", html)

    def test_static_file_is_copied_with_relative_path(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            source = root / "content"
            output = root / "public"
            nested = source / "files"
            nested.mkdir(parents=True)
            (nested / "note.txt").write_text("plain text", encoding="utf-8")

            build_site(source, output)

            self.assertEqual((output / "files" / "note.txt").read_text(encoding="utf-8"), "plain text")

    def test_index_page_lists_files_without_source_paths(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            source = root / "content"
            output = root / "public"
            source.mkdir()
            (source / "report.md").write_text("# Trip Plan\n\nBody text.\n", encoding="utf-8")

            build_site(source, output)

            html = (output / "index.html").read_text(encoding="utf-8")
            self.assertIn('<a href="report.html">Trip Plan</a>', html)
            self.assertNotIn("report.md", html)

    def test_default_static_assets_are_copied_from_static_sources(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            source = root / "content"
            output = root / "public"
            source.mkdir()

            build_site(source, output)

            self.assertEqual(
                (output / "static" / "style.css").read_text(encoding="utf-8"),
                project_path("static", "style.css").read_text(encoding="utf-8"),
            )
            self.assertEqual(
                (output / "static" / "script.js").read_text(encoding="utf-8"),
                project_path("static", "script.js").read_text(encoding="utf-8"),
            )

    def test_search_index_contains_markdown_text_and_front_matter_metadata(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            source = root / "content"
            output = root / "public"
            source.mkdir()
            (source / "report.md").write_text(
                "---\ntitle: Front Matter Title\ntags: [travel, report]\n---\n# Heading Title\n\nBody text.\n",
                encoding="utf-8",
            )

            build_site(source, output)

            search_index = json.loads((output / "search-index.json").read_text(encoding="utf-8"))
            self.assertEqual(search_index["version"], 1)
            self.assertEqual(len(search_index["items"]), 1)
            item = search_index["items"][0]
            self.assertEqual(item["title"], "Front Matter Title")
            self.assertEqual(item["url"], "report.html")
            self.assertEqual(item["kind"], "markdown")
            self.assertIn("travel", item["text"])
            self.assertIn("report", item["text"])
            self.assertIn("Body text.", item["text"])

            html = (output / "report.html").read_text(encoding="utf-8")
            self.assertNotIn("tags: [travel, report]", html)

    def test_search_index_contains_csv_text_but_not_static_files_or_indexes(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            source = root / "content"
            output = root / "public"
            nested = source / "reports"
            nested.mkdir(parents=True)
            (nested / "books.csv").write_text("title,notes\nExample,確認済み\n", encoding="utf-8")
            (source / "note.txt").write_text("plain text", encoding="utf-8")

            build_site(source, output)

            search_index = json.loads((output / "search-index.json").read_text(encoding="utf-8"))
            self.assertEqual(len(search_index["items"]), 1)
            item = search_index["items"][0]
            self.assertEqual(item["title"], "books")
            self.assertEqual(item["url"], "reports/books.html")
            self.assertEqual(item["kind"], "csv")
            self.assertIn("title", item["text"])
            self.assertIn("確認済み", item["text"])

    def test_generated_pages_include_search_ui_and_relative_search_index_url(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            source = root / "content"
            output = root / "public"
            nested = source / "reports"
            nested.mkdir(parents=True)
            (nested / "trip.md").write_text("# Trip\n", encoding="utf-8")

            build_site(source, output)

            root_html = (output / "index.html").read_text(encoding="utf-8")
            nested_html = (output / "reports" / "trip.html").read_text(encoding="utf-8")
            self.assertIn('data-search-index="search-index.json"', root_html)
            self.assertIn('data-search-index="../search-index.json"', nested_html)
            self.assertIn('name="q" type="search"', root_html)
            self.assertIn('id="site-search-pagination"', root_html)

    def test_invalid_csv_is_reported_but_valid_pages_are_generated(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            source = root / "content"
            output = root / "public"
            source.mkdir()
            (source / "ok.md").write_text("# OK\n", encoding="utf-8")
            (source / "bad.csv").write_text("a,b\n1\n", encoding="utf-8")

            result = build_site(source, output)

            self.assertEqual(len(result.errors), 1)
            self.assertTrue((output / "ok.html").exists())
            errors_html = (output / "errors.html").read_text(encoding="utf-8")
            self.assertIn("bad.csv", errors_html)
            self.assertIn("ColumnCountMismatch", errors_html)

    def test_output_path_collision_is_reported(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            source = root / "content"
            source.mkdir()
            (source / "same.csv").write_text("title\nA\n", encoding="utf-8")
            (source / "same.md").write_text("# Same\n", encoding="utf-8")

            errors = check_source(source, root / "public")

            self.assertEqual(len(errors), 1)
            self.assertEqual(errors[0].error_type, "Collision")

    def test_output_directory_inside_source_is_fatal(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            source = Path(temp) / "content"
            source.mkdir()

            with self.assertRaises(FatalBuildError):
                build_site(source, source / "public")


if __name__ == "__main__":
    unittest.main()
